# Generated by Django 5.0.3 on 2024-04-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=models.TextField(max_length=4000),
        ),
    ]
