# Generated by Django 5.0.3 on 2024-06-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_remove_publication_photo_pub_path_publication_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='id_pub',
            new_name='pub_name',
        ),
        migrations.AlterField(
            model_name='publication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publication',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
