# Generated by Django 5.0.3 on 2024-06-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0004_rename_id_pub_publication_pub_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publication',
            new_name='News',
        ),
    ]
